### ISSUE TITLE
get_git_revision failed error

### ISSUE THREAD

**Issue by cj-murphy** [airbrake/pybrake#25]
We have the following errors in our log files - Our deployment packages do not include the git directory.

`pybrake - ERROR - get_git_revision failed: [Errno 2] No such file or directory: '/var/task/.git/HEAD'`

Is it possible suppress these errors so they do not show in our application logs?

**Comment by vmihailenco** [comment]
I believe it is possible if you configure logging for pybrake - see https://github.com/airbrake/pybrake/blob/master/pybrake/utils.py#L5 and https://docs.python.org/3/library/logging.html

**Comment by srininara** [comment]
This does not seem to be a logging issue. If the docker image does not contain .git folder contents in it (because of .dockerignore), then the init of Notifier class raises an exception because the HEAD file is not present. This breaks pybrake initialization itself. Is it possible to change pybrake such a way that it does not require the HEAD file?

**Comment by vmihailenco** [comment]
What exception is thrown in your case?

**Comment by srininara** [comment]
pybrake - ERROR - get_git_revision failed: [Errno 2] No such file or directory: '/<project_name>/.git/HEAD

This is through from Notifier init method and hence the notifier initialization fails and hence cannot be used any more.

**Comment by vmihailenco** [comment]
That looks like a log message from `pybrake` logger. Besides it should disappear if you upgrade to v0.4.0, but it is still in beta.

**Comment by srininara** [comment]
Not sure it is from the logger. I think the place where this breaks is this:

https://github.com/airbrake/pybrake/blob/9693af1894f0969df52d6cf8225e272e42450d1a/pybrake/git.py#L49
And the call from notifier to this happens from here:
https://github.com/airbrake/pybrake/blob/9693af1894f0969df52d6cf8225e272e42450d1a/pybrake/notifier.py#L71

Just want to confirm if this is already fixed in v0.4.0. Also please let me know when will the version be out of beta and into GA?

**Comment by vmihailenco** [comment]
Those exceptions should be handled in https://github.com/airbrake/pybrake/blob/9693af1894f0969df52d6cf8225e272e42450d1a/pybrake/git.py#L11-L13

We still need more time to release v0.4

**Comment by gabelimon** [comment]
Can we get this ticket reopened? I'm seeing the same error on heroku. It would be nice if it would pick up the `SOURCE_VERSION`

**Comment by vmihailenco** [comment]
It is better to make sure you are using the last version and open a new issue with as much details as possible.
