### ISSUE TITLE
Add celery integration

### ISSUE THREAD

**Issue by vmihailenco** [airbrake/pybrake#89]
http://www.celeryproject.org/

Send exceptions that happen in celery tasks to airbrake

**Comment by tearoom6** [comment]
Since i wanna use Celery integration, I tried the most recent version (master branch https://github.com/airbrake/pybrake/commit/97d65b45e0a64d91806d2cb2c565241a7c2042e5) of pybrake.
Then, i got the following error logs.

```
2019-09-03 05:35:33,324 queues.py:141 pybrake ERROR - at least one group is required
```

It seems to be a error message sent by Airbrake server side.

Of cource, I know it's a result by using not-yet released version. But I'm glad if you can fix this problem. thank you!

**Comment by vmihailenco** [comment]
@tearoom6 should be fixed in master branch.

**Comment by tearoom6** [comment]
@vmihailenco No error log is shown in latest master branch. Thank for quick fix!

**Comment by phumpal** [comment]
Appears this is fixed. Please let us know otherwise.
